//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 

namespace Difi.Oppslagstjeneste.Klient.Scripts.XsdToCode.Code
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    internal partial class HentPersonerForespoersel
    {

        private informasjonsbehov[] informasjonsbehovField;

        private string[] personidentifikatorField;

        /// <remarks/>
        [XmlElement("informasjonsbehov")]
        public informasjonsbehov[] informasjonsbehov
        {
            get { return this.informasjonsbehovField; }
            set { this.informasjonsbehovField = value; }
        }

        /// <remarks/>
        [XmlElement("personidentifikator")]
        public string[] personidentifikator
        {
            get { return this.personidentifikatorField; }
            set { this.personidentifikatorField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    public enum informasjonsbehov
    {

        /// <remarks/>
        Person,

        /// <remarks/>
        Kontaktinfo,

        /// <remarks/>
        Sertifikat,

        /// <remarks/>
        SikkerDigitalPost,

        /// <remarks/>
        VarslingsStatus,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public partial class SikkerDigitalPostAdresse
    {

        private string postkasseadresseField;

        private string postkasseleverandoerAdresseField;

        /// <remarks/>
        public string postkasseadresse
        {
            get { return this.postkasseadresseField; }
            set { this.postkasseadresseField = value; }
        }

        /// <remarks/>
        public string postkasseleverandoerAdresse
        {
            get { return this.postkasseleverandoerAdresseField; }
            set { this.postkasseleverandoerAdresseField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public partial class Epostadresse
    {

        private System.DateTime sistOppdatertField;

        private bool sistOppdatertFieldSpecified;

        private System.DateTime sistVerifisertField;

        private bool sistVerifisertFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime sistOppdatert
        {
            get { return this.sistOppdatertField; }
            set { this.sistOppdatertField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sistOppdatertSpecified
        {
            get { return this.sistOppdatertFieldSpecified; }
            set { this.sistOppdatertFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime sistVerifisert
        {
            get { return this.sistVerifisertField; }
            set { this.sistVerifisertField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sistVerifisertSpecified
        {
            get { return this.sistVerifisertFieldSpecified; }
            set { this.sistVerifisertFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public partial class Mobiltelefonnummer
    {

        private System.DateTime sistOppdatertField;

        private bool sistOppdatertFieldSpecified;

        private System.DateTime sistVerifisertField;

        private bool sistVerifisertFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime sistOppdatert
        {
            get { return this.sistOppdatertField; }
            set { this.sistOppdatertField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sistOppdatertSpecified
        {
            get { return this.sistOppdatertFieldSpecified; }
            set { this.sistOppdatertFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime sistVerifisert
        {
            get { return this.sistVerifisertField; }
            set { this.sistVerifisertField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sistVerifisertSpecified
        {
            get { return this.sistVerifisertFieldSpecified; }
            set { this.sistVerifisertFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public partial class Kontaktinformasjon
    {

        private Mobiltelefonnummer mobiltelefonnummerField;

        private Epostadresse epostadresseField;

        /// <remarks/>
        public Mobiltelefonnummer Mobiltelefonnummer
        {
            get { return this.mobiltelefonnummerField; }
            set { this.mobiltelefonnummerField = value; }
        }

        /// <remarks/>
        public Epostadresse Epostadresse
        {
            get { return this.epostadresseField; }
            set { this.epostadresseField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://begrep.difi.no")]
    [XmlRoot(Namespace = "http://begrep.difi.no", IsNullable = false)]
    public partial class Person
    {

        private string personidentifikatorField;

        private reservasjon reservasjonField;

        private bool reservasjonFieldSpecified;

        private status statusField;

        private bool statusFieldSpecified;

        private varslingsstatus varslingsstatusField;

        private bool varslingsstatusFieldSpecified;

        private Kontaktinformasjon kontaktinformasjonField;

        private SikkerDigitalPostAdresse sikkerDigitalPostAdresseField;

        private byte[] x509SertifikatField;

        /// <remarks/>
        public string personidentifikator
        {
            get { return this.personidentifikatorField; }
            set { this.personidentifikatorField = value; }
        }

        /// <remarks/>
        public reservasjon reservasjon
        {
            get { return this.reservasjonField; }
            set { this.reservasjonField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool reservasjonSpecified
        {
            get { return this.reservasjonFieldSpecified; }
            set { this.reservasjonFieldSpecified = value; }
        }

        /// <remarks/>
        public status status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool statusSpecified
        {
            get { return this.statusFieldSpecified; }
            set { this.statusFieldSpecified = value; }
        }

        /// <remarks/>
        public varslingsstatus varslingsstatus
        {
            get { return this.varslingsstatusField; }
            set { this.varslingsstatusField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool varslingsstatusSpecified
        {
            get { return this.varslingsstatusFieldSpecified; }
            set { this.varslingsstatusFieldSpecified = value; }
        }

        /// <remarks/>
        public Kontaktinformasjon Kontaktinformasjon
        {
            get { return this.kontaktinformasjonField; }
            set { this.kontaktinformasjonField = value; }
        }

        /// <remarks/>
        public SikkerDigitalPostAdresse SikkerDigitalPostAdresse
        {
            get { return this.sikkerDigitalPostAdresseField; }
            set { this.sikkerDigitalPostAdresseField = value; }
        }

        /// <remarks/>
        [XmlElement(DataType = "base64Binary")]
        public byte[] X509Sertifikat
        {
            get { return this.x509SertifikatField; }
            set { this.x509SertifikatField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public enum reservasjon
    {

        /// <remarks/>
        JA,

        /// <remarks/>
        NEI,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public enum status
    {

        /// <remarks/>
        AKTIV,

        /// <remarks/>
        SLETTET,

        /// <remarks/>
        IKKE_REGISTRERT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://begrep.difi.no")]
    public enum varslingsstatus
    {

        /// <remarks/>
        KAN_IKKE_VARSLES,

        /// <remarks/>
        KAN_VARSLES,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class HentPersonerRespons
    {

        private Person[] personField;

        /// <remarks/>
        [XmlElement("Person", Namespace = "http://begrep.difi.no")]
        public Person[] Person
        {
            get { return this.personField; }
            set { this.personField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class HentEndringerForespoersel
    {

        private informasjonsbehov[] informasjonsbehovField;

        private long fraEndringsNummerField;

        /// <remarks/>
        [XmlElement("informasjonsbehov")]
        public informasjonsbehov[] informasjonsbehov
        {
            get { return this.informasjonsbehovField; }
            set { this.informasjonsbehovField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long fraEndringsNummer
        {
            get { return this.fraEndringsNummerField; }
            set { this.fraEndringsNummerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class HentEndringerRespons
    {

        private Person[] personField;

        private long fraEndringsNummerField;

        private long tilEndringsNummerField;

        private long senesteEndringsNummerField;

        /// <remarks/>
        [XmlElement("Person", Namespace = "http://begrep.difi.no")]
        public Person[] Person
        {
            get { return this.personField; }
            set { this.personField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long fraEndringsNummer
        {
            get { return this.fraEndringsNummerField; }
            set { this.fraEndringsNummerField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long tilEndringsNummer
        {
            get { return this.tilEndringsNummerField; }
            set { this.tilEndringsNummerField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long senesteEndringsNummer
        {
            get { return this.senesteEndringsNummerField; }
            set { this.senesteEndringsNummerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class HentPrintSertifikatForespoersel
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class HentPrintSertifikatRespons
    {

        private string postkasseleverandoerAdresseField;

        private byte[] x509SertifikatField;

        /// <remarks/>
        public string postkasseleverandoerAdresse
        {
            get { return this.postkasseleverandoerAdresseField; }
            set { this.postkasseleverandoerAdresseField = value; }
        }

        /// <remarks/>
        [XmlElement(DataType = "base64Binary")]
        public byte[] X509Sertifikat
        {
            get { return this.x509SertifikatField; }
            set { this.x509SertifikatField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true,
        Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02")]
    [XmlRoot(Namespace = "http://kontaktinfo.difi.no/xsd/oppslagstjeneste/16-02",
        IsNullable = false)]
    public partial class Oppslagstjenesten
    {

        private string paaVegneAvField;

        /// <remarks/>
        public string PaaVegneAv
        {
            get { return this.paaVegneAvField; }
            set { this.paaVegneAvField = value; }
        }
    }
}